#source 'https://github.com/CocoaPods/Specs.git'

target 'StockToolz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '5.2.2'

  target 'StockToolzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
