source 'https://bitbucket.org/flowtoolz/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'StockToolz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '4.0.0'
    pod 'PureLayout', '3.0.2'
    pod 'Flowtoolz', '0.1.1' #, :path=> '../../FlowtoolzCocoapod'

  target 'StockToolzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
